### ISSUE TITLE
kaggle上的notebook的问题。

### ISSUE THREAD

**Issue by bscncsu** [SonwYang/building-extraction#1]
Hi bro,

您的kaggle上的notebook在kaggle上运行不了，总是无法下载模型，我把您kaggle上的notebook复制到谷歌的colab上跑，可以正常跑，但是跑一百个epoch之后得到的模型，把用于训练的图像弄进去进行预测，总是得不到建筑类型，请问是什么问题？

期待您的回复，

谢谢！
zhen

**Comment by SonwYang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonwYang/building-extraction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 上午9:12
收件人:&nbsp;"SonwYang/building-extraction"<building-extraction@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SonwYang/building-extraction] kaggle上的notebook的问题。 (#1)





 
Hi bro,
 
您的kaggle上的notebook在kaggle上运行不了，总是无法下载模型，我把您kaggle上的notebook复制到谷歌的colab上跑，可以正常跑，但是跑一百个epoch之后得到的模型，把用于训练的图像弄进去进行预测，总是得不到建筑类型，请问是什么问题？
 
期待您的回复，
 
谢谢！
 zhen
 
也许你没有乘以255， 0和1人眼是看不出来的
